config/routes.rb
Rails.application.routes.draw do
  get 'log_in' => 'sessions#new', as: :log_in
  get 'log_out' => 'sessions#destroy', as: :log_out

  get 'sign_up' => 'users#new', as: :sign_up

  get 'welcome' => 'home#index', as: :welcome
  root 'home#index'

  resources :users
  resources :to_dos
  resources :sessions
  get 'to_dos/:id/finish', to: 'to_dos#finish', as: :finish_to_do
end

app/models/app_filter/to_do.rb
module AppFilter
  class ToDo
    include ActiveModel::Model
    attr_accessor :title, :status, :user
    attr_reader :results

    def initialize(attributes = {})
      super(attributes)
      raise 'user can\'t be nil' unless user
      raise 'user aren\'t a User object' if user.class != User
      filter_to_dos
    end

    private

    def filter_to_dos
      @results = ::ToDo.find_all(user)
      filter_by_status if status && ::ToDo::STATUS.include?(status.to_sym)
      filter_delayed if status && status.to_sym == :delayed
      filter_by_title if title && !title.empty?
    end

    def filter_by_status
      @results = @results.where(status: status, user_id: user.id)
    end

    def filter_delayed
      @results = @results.where(:deadline.lt => Date.today, user_id: user.id)
    end

    def filter_by_title
      @results = @results.where(title: /#{title}/i, user_id: user.id)
    end
  end
end

app/models/to_do.rb
class ToDo
  include Mongoid::Document
  include Mongoid::Enum
  strip_attributes

  field :title, type: String
  field :description, type: String
  field :deadline, type: Date
  field :finished_at, type: Date
  enum :status, [:pending, :finished], default: :pending

  belongs_to :user

  validates :title, :deadline, presence: true
  validates :deadline, date: { after_or_equal_to: Proc.new { Date.today } }

  scope :find_all, lambda { |user| where(user_id: user.id) }
  scope :find_finished, lambda { |user| where(status: :finished, user_id: user.id)}
  scope :find_pending, lambda { |user| where(status: :pending, user_id: user.id)}
  scope :find_delayed, lambda { |user|
    where(:deadline.lt => Date.today, user_id: user.id)
  }

  def self.icon
    :book
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  field :email, type: String
  field :password_hash, type: String

  attr_accessor :password

  before_save :encripty_password

  has_many :to_dos

  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def encripty_password
    self.password_hash = BCrypt::Password.create(password) if password.present?
  end

  def password_hash
    @password_hash ||= BCrypt::Password.new(self[:password_hash])
  end

  def self.authenticate(email, password)
    user = find_by(email: email)
    return user if user && user.password_hash == password
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html, :json

  helper_method :current_user
  before_filter :verify_logged_in

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def verify_logged_in
    unless current_user
      session[:user_id] = nil
      redirect_to log_in_path, alert: 'Faça login para continuar'
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :verify_logged_in, only: [:index]

  def index
    if current_user
      render 'welcome_user'
    else
      render 'welcome_stranger'
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_logged_in, only: [:new, :create]

  def new
  end

  def create
    dt = user_params
    user = User.authenticate(dt[:email], dt[:password])

    if user
      session[:user_id] = user.id.to_s
      redirect_to root_url, notice: 'Logado com sucesso'
    else
      flash.now.alert = 'Email ou senha inválido'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to log_in_path, notice: 'Logout realizado'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  before_action :set_to_do, only: [:edit, :update, :destroy, :finish]

  def index
    collection
    respond_with @to_dos
  end

  def new
    @to_do = ToDo.new
  end

  def create
    @to_do = ToDo.new(to_do_params)
    @to_do.user = current_user
    @to_do.save
    respond_with(@to_do, location: -> { to_dos_path })
  end

  def update
    @to_do.update(to_do_params)
    respond_with(@to_do, location: -> { to_dos_path })
  end

  def finish
    @to_do.status = :finished
    @to_do.finished_at = Date.today

    # For time reason, respond_to instead of a custom responder
    respond_to do |format|
      if @to_do.save
        format.html { redirect_to to_dos_path, notice: 'Tarefa finalizada com sucesso' }
      else
        format.html { redirect_to to_dos_path, alert: 'Não foi possível finalizar a tarefa' }
      end
    end
  end

  def destroy
    @to_do.destroy
    respond_with(@to_do, location: -> { to_dos_path })
  end

  private

  def set_to_do
    @to_do = ToDo.find(params[:id])
  end

  def collection
    @params = filter_params
    filter = AppFilter::ToDo.new(@params.merge(user: current_user))
    @to_dos = filter.results
    @to_dos = @to_dos.paginate(page: params[:page])
  end

  def filter_params
    params.permit(:title, :status).delete_if { |_k, v| !v.present? }
  end

  def to_do_params
    params.require(:to_do).permit(:title, :description, :deadline,
                                  :finished_at, :status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :verify_logged_in, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      session[:user_id] = @user.id.to_s
      redirect_to root_url, notice: 'Bem-vindo!'
    else
      render :new
    end
  end

  private

  def users_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def msg_error(model)
    model_name = model.model_name.human
    count = model.errors.count
    error = I18n.t('words.error', count: model.errors.count)
    "#{model_name}: #{count} #{error}"
  end
end

app/helpers/fields_helper.rb
# Create form_for fields
module FieldsHelper
  def ftext_field(f, attr, opts = {})
    field_base(f, attr, :text_field, opts)
  end

  def fdate_field(f, attr, opts = {})
    value = f.object.send(attr)
    opts[:value] = value ? I18n.l(value) : nil
    field_base(f, attr, :text_field, opts)
  end

  def farea_field(f, attr, opts = {})
    field_base(f, attr, :text_area, opts)
  end

  def fpassword_field(f, attr, opts = {})
    field_base(f, attr, :password_field, opts)
  end

  def field_base(f, attr, type, opts = {})
    opts[:class] << ' form-control' if opts[:class]
    opts[:class] ||= 'form-control'
    label = f_label(f, attr)
    input = f.send(type, attr, opts)
    content_tag(:div, class: 'form-group') do
      label + input
    end.html_safe
  end

  private

  def f_label(f, attr)
    klass = 'control-label'
    f.label(attr, nil, class: klass)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
# Just an another way to create buttons in app
module LinksHelper
  Todo::CONSTANTS::BUTTONS.each do |k, v|
    define_method "button_to_#{k}" do |url, opts = {}|
      opts[:'data-container'] = 'body'
      opts[:class] << v[:btn] if opts[:class]
      opts[:class] ||= v[:btn]
      button_base(k, v[:icon], url, opts)
    end
  end

  def button_base(type, icon, url, opts = {})
    opts[:class] << ' btn tip'
    label = opts.include?(:label) ? opts[:label] : t("buttons.#{type}")
    opts[:title] = label.nil? || label.empty? ? t("buttons.#{type}") : nil
    icon = fa_icon(icon, text: label)
    content_tag(:a, icon, opts.merge(href: url))
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
  def label_status(to_do, status)
    txt = to_do.send("#{status}_i18n")
    # Check if is a delayed to_do
    return content_tag(:span, txt, class: 'label label-danger') if to_do.deadline < Date.today

    case to_do.send(status)
    when :pending then klass = 'label label-warning'
    when :finished then klass = 'label label-success'
    else klass = 'label label-default'
    end
    content_tag(:span, txt, class: klass)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.slim
.page-header
  h1 Bem vindo a to-do list!

app/views/home/welcome_stranger.html.slim
.page-header
  h1 Bem vindo ao melhor todo list existente.

.row
  .col-xs-12
    h3
      | Para continuar
      a href=log_in_path
        | Faça login
      | ou
      a href=sign_up_path
        | Cadastre-se!

app/views/home/welcome_user.html.slim
.page-header
  h3 "#{current_user.email}, bem vindo!"

.panel.panel-default
  .panel-body
    h4 Resumo das tarefas:
    h4
      ul
        li Total:  #{ToDo.find_all(current_user).count}
        li Realizadas: #{ToDo.find_finished(current_user).count}
        li Pendentes: #{ToDo.find_pending(current_user).count}
        li Atrasadas: #{ToDo.find_delayed(current_user).count}

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content=""
    meta name="author" content=""
    title
      | Tarefas
    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body class= "#{controller_name} #{action_name}"
    = render 'shared/navbar'
    .container
      = render 'shared/flash_messages', flash: flash
      = yield

app/views/shared/_error_messages.html.slim
- if model.errors.any?
  #error_explanation
    .panel.panel-danger
      .panel-heading
        h3.panel-title
          = msg_error(model)
      .panel-body
        ul.list-unstyled
          - model.errors.full_messages.each do |msg|
            li = msg

app/views/shared/_flash_messages.html.slim
#flash-container
  - flash.each do |name, msg|
    - fl = Todo::CONSTANTS::FLASH_MESSAGES[name.to_sym]
    div.alert.alert-dismissable.fade.in class="alert-#{fl[:body]}" role='alert'
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true" &times;
        span.sr-only Close
      = fa_icon fl[:icon], text: msg

app/views/shared/_navbar.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container
    .navbar-header
      button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
        span.sr-only
          | Tarefas
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Todo list", root_path, class: "navbar-brand"
    #navbar.collapse.navbar-collapse
      - if current_user
        ul.nav.navbar-nav
          li
            a href=root_path
              = fa_icon 'home', text: 'Home'
          li
            a href=to_dos_path
              = fa_icon ToDo.icon, text: 'Tarefas'
        ul.nav.navbar-nav.navbar-right
          p.navbar-text
            = current_user.email
          li
            a href=log_out_path
              = fa_icon 'sign-out', text: 'Sair'
      - else
        ul.nav.navbar-nav
          li
            a href=log_in_path
              = fa_icon 'sign-in', text: 'Entrar'
          li
            a href=sign_up_path
              = fa_icon 'user-plus', text: 'Cadastrar'

app/views/to_dos/_form.html.slim
= form_for @to_do do |f|
  .row
    .col-xs-12
      = render 'shared/error_messages', model: @to_do
  .row
    .col-xs-7
      = ftext_field f, :title
    .col-xs-5
      = fdate_field f, :deadline, class: 'date'
  - unless @to_do.new_record?
    .row
      .col-xs-7
        = fdate_field f, :finished_at, class: 'date'
      .col-xs-5
        .form-group
          = f.label :status
          = f.select :status, options_for_select(ToDo.status_values), {}, { class: 'form-control' }
  .row
    .col-xs-12
      = farea_field f, :description, rows: 5

  .row
    .col-xs-12
      hr
      .actions
        - unless @to_do.new_record?
          = link_to fa_icon(:times, text: 'Apagar'), @to_do, class: 'btn btn-danger', data: { confirm: 'Você tem certeza?' }, method: :delete

        = f.submit 'Salvar', class: 'btn btn-primary submit'

app/views/to_dos/edit.html.slim
.page-header
  .row
    .col-xs-7
      h3= fa_icon ToDo.icon, text: 'Editando tarefa'
    .col-xs-5.text-right.h3
      = button_to_back to_dos_path

== render 'form'

app/views/to_dos/index.html.slim
.page-header
  .row
    .col-xs-7
      h3 = fa_icon ToDo.icon, text: ' Tarefas'
    .col-xs-5.h3.text-right
      = button_to_add new_to_do_path

= form_tag to_dos_path(@params), method: :get do
  .form-group
    = label_tag :search, 'Procurar', class: 'control-label'
    .input-group
      input type= 'text' name= 'title' value= @params[:title] class= 'form-control'
      span.input-group-btn
        button type= 'submit' class= 'btn btn-default'
          | Procurar!

hr
.row
  .col-sm-6
    - unless @params.empty?
      a.btn.btn-danger href= to_dos_path
        = fa_icon :times, text: ' Limpar filtros'

  .col-sm-6.text-right
    .btn.btn-group
      - ToDo.status_values.each do |val|
        a.btn.btn-default class=('active' if @params[:status]  == val[1].to_s) href=to_dos_path(@params.merge(status: val[1]))
          = val[0]


hr
table.table.table-striped
  thead
    tr
      th
      th= ToDo.human_attribute_name(:title)
      th= ToDo.human_attribute_name(:description)
      th= ToDo.human_attribute_name(:deadline)
      th= ToDo.human_attribute_name(:finished_at)
      th.text-center= ToDo.human_attribute_name(:status)
      th

  tbody
    - @to_dos.each do |to_do|
      tr
        td
        td = to_do.title
        td = truncate(to_do.description, lenght: 20)
        td = l to_do.deadline
        td = to_do.finished_at? ? l(to_do.finished_at) : ''
        td = label_status to_do, :status
        td.col-xs-2.text-right
          .btn-group
            = button_to_finish finish_to_do_path(to_do), label: nil
            = button_to_edit edit_to_do_path(to_do), label: nil

.row
  .col-xs-12.text-center
    = will_paginate @to_dos

app/views/to_dos/new.html.slim
.page-header
  .row
    .col-xs-7
      h3= fa_icon ToDo.icon, text: 'Nova tarefa'
    .col-xs-5.text-right.h3
      = button_to_back to_dos_path

== render 'form'

app/views/users/new.html.slim
.page-header
  h1 Cadastre-se na mais incrível to-do list!

= form_for @user do |f|
  .row
    .col-xs-12
      = render 'shared/error_messages', model: @user
  .row
    .col-xs-offset-3.col-xs-6
      .panel.panel-default
        .panel-body
          = ftext_field f, :email
          = fpassword_field f, :password
          = fpassword_field f, :password_confirmation
          hr
          = f.submit 'Cadastrar', class: 'submit btn btn-primary'